from fastapi import FastAPI, Query, HTTPException, status, WebSocket, WebSocketDisconnect
from pymongo import MongoClient
from pymongo.errors import PyMongoError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pathlib import Path
from pydantic import BaseModel, Field
from dotenv import load_dotenv, find_dotenv
import os
import hashlib
import secrets
from datetime import datetime, timedelta
import asyncio
from concurrent.futures import ThreadPoolExecutor
from contextlib import asynccontextmanager, contextmanager
from threading import Lock, Thread, ThreadError, Condition
from collections import defaultdict

print("Loaded dotenv:", load_dotenv(find_dotenv(".env")))

# ----- Database Setup -----
uri = os.getenv("DB_LINK")
client = MongoClient(uri)
db = client["MyDB"]
collection = db["MyCollection"]

# ----- THREADING -----
# Create a dedicated thread pool for downloads
download_executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="download")

# Separate event loop for download thread
download_loop = None
download_thread = None

# ----- FastAPI Lifespan Management -----

def init_download_thread():
    """Initialize download thread with its own event loop"""
    global download_loop
    download_loop = asyncio.new_event_loop()
    asyncio.set_event_loop(download_loop)
    download_loop.run_forever()

# Start download thread on startup
async def startup_event():
    global download_thread
    download_thread = Thread(target=init_download_thread, daemon=True)
    download_thread.start()
    
    # Wait for loop to be ready
    while download_loop is None:
        await asyncio.sleep(0.01)
    
    print("✅ Download thread initialized")

# Stop download thread on shutdown
async def shutdown_event():
    if download_loop:
        download_loop.call_soon_threadsafe(download_loop.stop)

# Manage the process over its lifetime (start; run; cleanup)
@asynccontextmanager
async def lifespan(app: FastAPI):
    await startup_event()
    try:
        yield
    finally:
        await shutdown_event()

# ----- FastAPI App -----
app = FastAPI(
    title="Robot Inventory API",
    description="CRUD API for managing robots stored in MongoDB.",
    version="1.0.0",
    lifespan=lifespan
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ----- Locks & Threading -----
# Generated by our friend, ChatGPT
class GroupLock:
    def __init__(self):
        self._cond = Condition()
        self._global_locked = False
        self._token_locks = defaultdict(lambda: Lock())
        self._active_token_count = 0

    def acquire_token(self, token):
        # wait if global lock is held, then mark active and acquire per-token lock
        with self._cond:
            while self._global_locked:
                self._cond.wait()
            self._active_token_count += 1
        # serialize access to this token
        self._token_locks[token].acquire()

    def release_token(self, token):
        # release per-token lock then update active count and notify
        try:
            self._token_locks[token].release()
        finally:
            with self._cond:
                self._active_token_count -= 1
                if self._active_token_count == 0:
                    self._cond.notify_all()

    def acquire_global(self):
        # wait until no active token locks, then take global flag
        with self._cond:
            while self._global_locked or self._active_token_count > 0:
                self._cond.wait()
            self._global_locked = True

    def release_global(self):
        with self._cond:
            self._global_locked = False
            self._cond.notify_all()

    @contextmanager
    def token(self, token):
        self.acquire_token(token)
        try:
            yield
        finally:
            self.release_token(token)

    @contextmanager
    def global_lock(self):
        self.acquire_global()
        try:
            yield
        finally:
            self.release_global()

# ----- Token & Session Management -----

# Store active connections by token: {token: websocket}
upload_connections: dict[str, WebSocket] = {}
download_connections: dict[str, WebSocket] = {}

# Store token metadata: {token: {username, created_at, last_seen}}
token_metadata: dict[str, dict] = {}
 

# Create Locks for each token, allowing per-client upload
# and download to be multi-threaded avoiding race conditions
upload_locks = GroupLock()
download_locks = GroupLock()
metadata_locks = GroupLock()

# Token expiry time (7 days)
TOKEN_EXPIRY = timedelta(days=7)

def generate_token() -> str:
    """Generate a secure random token"""
    return secrets.token_urlsafe(32)

def is_token_valid(token: str) -> bool:
    # Lock the token metadata during execution
    with metadata_locks.token(token):
        """Check if token exists and hasn't expired"""
        if token not in token_metadata:
            return False
        
        metadata = token_metadata[token]
        created_at = metadata.get("created_at")
        
        if not created_at:
            return False
        
        # Check if token expired
        if datetime.now() - created_at > TOKEN_EXPIRY:
            # Lock the token upload and download websockets
            with upload_locks.token(token), download_locks.token(token):
                # Clean up expired token
                if token in upload_connections:
                    del upload_connections[token]
                if token in download_connections:
                    del download_connections[token]
                del token_metadata[token]
                return False
        return True

# ----- Pydantic Models -----

class TokenRequest(BaseModel):
    username: str = Field(..., min_length=3, max_length=16, description="Username between 3-16 characters")

class TokenResponse(BaseModel):
    token: str
    username: str
    expires_in: int  # seconds until expiry

# ----- ROUTES -----

@app.get(
    "/",
    tags=["System"],
    summary="Serve index.html",
    response_description="Returns the homepage HTML file."
)
def read_root():
    path = Path(__file__).resolve().parent / "index.html"
    return FileResponse(path, media_type="text/html")

@app.post(
    "/ws/auth/token",
    tags=["Authentication"],
    summary="Generate authentication token",
    response_model=TokenResponse,
    response_description="Returns a new authentication token for WebSocket connection"
)
def create_token(request: TokenRequest):
    """
    Generate a new authentication token for a user.
    The token is valid for 7 days and allows WebSocket connection.
    """
    username = request.username.strip()
    
    # Validate username
    if len(username) < 3 or len(username) > 16:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Username must be between 3 and 16 characters"
        )
    
    # Generate new token
    token = generate_token()
    
    # Lock the token metadata during execution
    with metadata_locks.token(token):
        # Store token metadata
        token_metadata[token] = {
            "username": username,
            "created_at": datetime.now(),
            "last_seen": datetime.now(),
            "files": {}
        }
    
    print(f"✨ Generated token for user: {username}")
    
    return TokenResponse(
        token=token,
        username=username,
        expires_in=int(TOKEN_EXPIRY.total_seconds())
    )

# ----- WEBSOCKET ----- 

async def send_to_clients(sender_token: str, event_type: str, payload: any, excluding=None):
    # Lock the sender metadata to retreive username
    with metadata_locks.token(sender_token):
        sender_name = token_metadata[sender_token]["username"]
    
    # Breifly lock all download tokens
    with download_locks.global_lock():
        # Get the token list
        client_tokens = list(download_connections.keys())

    for client_token in client_tokens:
        # Lock the client's download websocket
        with download_locks.token(client_token):
            # Get the client's websocket
            client = download_connections.get(client_token)

        # There is no websocket, the client disconnected
        if not client or client.get("disconnected"):
            continue

        # Skip the client, if they were the sender
        if client is not excluding:
            # Assemble the data to send
            data = {
                "username": sender_name,
                "event_type": event_type,
                "payload": payload
            }
            
            await client.send_json(data)
    print(f"Sent to {len(client_tokens)} clients")

async def send_file_to_clients(sender_token: str, file_name: str, file: dict, excluding=None):
    # Send file data in chunks
    chunk_size = 1024 * 64  # 64KB chunks
    
    # File data
    content = list(file["content"])
    filesize = len(content)

    # Lock all download websockets to get the client count
    with download_locks.global_lock():
        # Number of clients
        client_count = len(download_connections.values())
    
    print(f"Sending {filesize / chunk_size} chunks to {client_count} clients...")
    for i in range(0, filesize, chunk_size):
        # Get bytes chunk
        chunk = content[i:i + chunk_size]
        # print(f"Size: {len(chunk)} bytes")

        if i == 0:
            event_type = "file_start"   # The first chunk
        elif i + chunk_size < filesize:
            event_type = "file"         # Anything in-between
        else:
            event_type = "file_end"     # The last chunk

        # Make a payload with the bytes and filename (for concurrent downloads)
        payload = { "file_name": file_name, "bytes": chunk }

        # This is the first chunk to send
        if event_type == "file_start":
            # Include non-functional, verifying data with first chunk
            # That way if existing data matches the hash and name, can ignore
            payload["size"] = filesize
            payload["timestamp"] = file["timestamp"]
            payload["hash"] = file["hash"]
            payload["algorithm"] = file["algorithm"]

        # Send the chunk to the client
        await send_to_clients(sender_token, event_type, payload, excluding=excluding)

        if (i // chunk_size) % 3 == 0:
            await asyncio.sleep(0)  # Yield to event loop

    print("Done.")

async def send_error(receiver, event_type, payload):
    await receiver.send_json({
        "username": "system",
        "event_type": event_type,
        "payload": payload
    })

waiting_for_file = False # Indicates whether the websocket is waiting on file contents
file_name = str() # Name of the file
file_data = bytes() # Byte Array -- Pre-declared so as to update later
hash_alg = "sha256" # The algorithm to use when hashing

def upload_file(event_type: str, payload: dict, token: str):
    # The filename of the upload
    file_name = payload.get("file_name")
    # The file content
    content = bytes(payload.get("bytes"))
    # The expected file hash/algorithm (optional)
    client_hash = str(payload.get("hash")).lower()
    client_algorithm = str(payload.get("algorithm")).lower()

    if not file_name:
        print("!!! No File Name !!!")
        return None
    
    # Lock the token metadata during execution
    # Used to retreive username and edit file
    with metadata_locks.token(token):
        # The sender's username
        username = token_metadata[token]["username"]
        # The stored filedata for the client's file, if exists
        upload = token_metadata[token]["files"].get(file_name)

        # The upload storage has pre-existing file data
        if (upload and upload.get("content")):
            # Increment the file byte-data
            upload["content"] += content
        
        # The start of a new file (overwrites existing of same name)
        if event_type == "file_start":
            # Create a new file with corresponding name
            upload = {} # Empty Dictionary

            # Initialize defaults
            upload.setdefault("in_progress", True)          # File is incomplete
            upload.setdefault("timestamp", datetime.timestamp(datetime.now()))  # When the file was received 
            upload.setdefault("content", content)           # Default content
            upload.setdefault("hash", None)                 # No hash
            upload.setdefault("algorithm", None)            # No hash-algorithm
        # The last piece of an uploaded file
        elif event_type == "file_end":
            print(f"Received from {token[:8]}... ({username}): {file_name} ({len(upload["content"])} bytes)")
            
            # Verify file integrity using client hash
            if client_hash and client_algorithm:
                server_hash = hashlib.new(client_algorithm, bytes(upload["content"])).hexdigest()

                # Hash verification failed
                if server_hash != client_hash:
                    print(
                        f"""
                        Failed to verify hash for file from {token[:8]}... ({username})
                            File Name:  {file_name}
                            Expected:   {client_hash}
                            Calculated: {server_hash}
                            Algorithm:  {client_algorithm}
                        """
                    )

                    # Clear the upload data
                    upload = None

            # Ensure the upload is still valid
            # -- May not be if client_hash verified
            if upload is not None:
                # Verify file integrity with server hash
                upload["hash"] = hashlib.new(hash_alg, bytes(upload["content"])).hexdigest()
                upload["algorithm"] = hash_alg

                print(
                    f"""
                    Hash calculated for file (from {token})      
                        File Name:  {file_name}
                        Calculated: {upload["hash"]}
                        Algorithm:  {upload["algorithm"]}
                    """
                )

                # Mark the upload as complete (remove the attribute)
                upload.pop("in_progress")

        # Update the token_metadata saved filedata
        token_metadata[token]["files"][file_name] = upload

        # Return the updated filedata
        return token_metadata[token]["files"][file_name], file_name

def upload_message(event_type: str, payload: dict, token: str):
    # Lock the token metadata to retreive username
    with metadata_locks.token(token):
        username = token_metadata[token]["username"]

    text = payload.get("text")
    # Optional timestamp payload
    timestamp = payload.get("timestamp") or datetime.timestamp(datetime.now())

    # Forward the message to other clients
    print(f"Received from {token[:8]}... ({username}): {text}")

    # Return the text and timestamp
    return text, timestamp

# Schedule downloads on the download thread
async def handle_download(event_type, params, exclude_token=None):
    # print(f"DOWNLOAD: {event_type}")

    if download_loop is None:
        print("⚠ download_loop not ready; skipping")
        return
    
    """Schedule download tasks on download thread"""
    if event_type == "file":
        # Run on download thread's event loop
        future = asyncio.run_coroutine_threadsafe(
            send_file_to_clients(params[0], params[1], params[2], exclude_token),
            download_loop
        )
    elif event_type == "message":
        future = asyncio.run_coroutine_threadsafe(
            send_to_clients(params[0], params[1], params[2], exclude_token),
            download_loop
        )

def handle_upload(token: str, data: dict):
    # Lock the token metadata to retreive username
    with metadata_locks.token(token):
        # The client's username
        username = token_metadata[token]["username"]

    # Data from client
    event_type = str(data.get("event_type"))
    payload = data.get("payload")
    sender = str(data.get("username"))

    # print(f"UPLOAD: {event_type}")

    # The sender updated their username
    if sender != username:
        print(f"Updating username for ({token[:8]}): {username} --> {sender}")

        # Lock the token metadata to update the username
        with metadata_locks.token(token):
            # Update the client's username
            token_metadata[token]["username"] = sender
            # TODO Send updated notification, for clients to update UI?

    # --- HEARTBEAT LOGIC ---
    # if event_type == "ping":
    #     await websocket.send_json({ "username": "server", "message": "pong" })
    #     return # Skip the rest of the loop so we don't echo "ping" to chat
    # --- UPLOAD HANDLING ---
    if event_type.startswith("file"):
        # Handle the file upload
        file, file_name = upload_file(event_type, payload, token)

        # The file is incomplete
        if file and file.get("in_progress"):
            # Move onto the next upload
            return

        print(f"Received from {sender}: {file_name} ({len(file.get("content"))} bytes)")

        # Queue the next download
        # Send the complete file to all connected clients
        asyncio.create_task(handle_download("file", (token, file_name, file), None)) #token
    # --- MESSAGE HANDLING ---
    elif event_type == "message":
        text, timestamp = upload_message(event_type, payload, token)

        # Construct the payload
        payload = { "timestamp": timestamp, "text": text }

        # Queue the next download
        asyncio.create_task(handle_download("message", (token, "message", payload), None)) #token
        
        # Don't exclude the sender, since I removed the logic from App
        # asyncio.create_task(send_to_clients(token, "message", payload))
    # -----------------------

@app.websocket("/ws/upload")
async def upload_endpoint(websocket: WebSocket, token: str = Query(...)):
    # Validate token
    if not is_token_valid(token):
        await websocket.close(code=1008, reason="Invalid or expired token")
        print("UPLOAD: Rejected connection: Invalid token")
        return
    
    try:
        await websocket.accept()
            
        # Lock the client's upload websocket
        with upload_locks.token(token):
            # Check if there's already a connection with this token
            if upload_connections.get(token):
                print(f"UPLOAD: Client reconnected: (Token: {token[:8]}...)")
            else:
                print(f"UPLOAD: New client connected: (Token: {token[:8]}...)")

            # Store the new connection
            upload_connections[token] = websocket

        # Lock the token metadata to update the 'last_seen'
        with metadata_locks.token(token):
            token_metadata[token]["last_seen"] = datetime.now()

        while True:
            # Wait for message from client
            data = await websocket.receive_json()
            
            # Run the general upload handler
            handle_upload(token, data)

    except WebSocketDisconnect:
        # Lock the client's upload websocket
        with upload_locks.token(token):
            print(f"UPLOAD: Client disconnected ({len(upload_connections.values())} clients)")
            upload_connections[token] = { "disconnected": True }
    except Exception as e:
        print("Unexpected error:", e)
        try:
            # Lock the client's upload websocket
            with upload_locks.token(token):
                print(f"UPLOAD: Client disconnected ({len(upload_connections.values())} clients)")
                upload_connections[token] = { "disconnected": True }
            await websocket.close()
        except:
            pass

@app.websocket("/ws/download")
async def download_endpoint(websocket: WebSocket, token: str = Query(...)):
    # Validate token
    if not is_token_valid(token):
        await websocket.close(code=1008, reason="Invalid or expired token")
        print("DOWNLOAD: Rejected connection: Invalid token")
        return
    
    try:
        await websocket.accept()
        
        # Lock the client's download websocket
        with download_locks.token(token):
            # Check if there's already a connection with this token
            if download_connections.get(token):
                print(f"DOWNLOAD: Client reconnected: (Token: {token[:8]}...)")
            else:
                print(f"DOWNLOAD: New client connected: (Token: {token[:8]}...)")
        
            # Store the new connection
            download_connections[token] = websocket

        # Lock the token metadata to update 'last_seen'
        with metadata_locks.token(token):
            token_metadata[token]["last_seen"] = datetime.now()

        while True:
            # Do nothing -- Download only exists to send to the client
            await asyncio.sleep(60)


    except WebSocketDisconnect:
        # Lock the client's download websocket
        with download_locks.token(token):
            print(f"DOWNLOAD: Client disconnected ({len(download_connections.values())} clients)")
            download_connections[token] = { "disconnected": True }
    except Exception as e:
        print("Unexpected error:", e)
        try:
            # Lock the client's download websocket
            with download_locks.token(token):
                print(f"DOWNLOAD: Client disconnected ({len(download_connections.values())} clients)")
                download_connections[token] = { "disconnected": True }
                await websocket.close()
        except:
            pass